name: CoderCo Secrets CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: use secrets
      run: echo "The secret value is ${{ secrets.MY_SECRET }}"